describe("Test the harvest report default values", () => {
  beforeEach(() => {
      cy.login("manager1", "farmdata2")
      cy.visit("/farm/fd2-school/fd2")
  })

  it("Check Custom Table Headers", () => {
    cy.get("[data-cy=generate-report-button]").click()
    cy.get("[data-cy=h0]")
    .should("have.text","Date")
    cy.get("[data-cy=h1]")
    .should("have.text","Area")
    cy.get("[data-cy=h2]")
    .should("have.text","Crop")
    cy.get("[data-cy=h3]")
    .should("have.text","Yield")
    cy.get("[data-cy=h4]")
    .should("have.text","Unit")
    cy.get("[data-cy=r0]")
    .children().should("have.length","5")
  })

  it("Check generated Crop",()=>{
    cy.get ("[data-cy=crop-select] > [data-cy=dropdown-input] ").select("ARUGULA")
    cy.get("[data-cy=generate-report-button]").click()
    cy.get ("[data-cy=table-body]").children().should("have.length","4")
    cy.get("[data-cy=td-r1c2]")
    .should("have.text", 'ARUGULA     ')
    cy.get("[data-cy=td-r2c2]")
    .should("have.text", 'ARUGULA     ')
    cy.get("[data-cy=td-r3c2]")
    .should("have.text", 'ARUGULA     ')
    cy.get("[data-cy=td-r0c2]")
    .should("have.text", 'ARUGULA     ')
  })
})
